# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
