# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0002_job_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=100)),
                ('volunteer_email', models.EmailField(max_length=100)),
                ('volunteer_grade', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='job',
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mande.Job'),
        ),
    ]
