# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0003_auto_20160128_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_detail',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
