# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0005_auto_20160224_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
