# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mande', '0006_auto_20160301_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_detail',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_email',
            field=models.EmailField(max_length=100),
        ),
    ]
